# Generated by Django 6.0.4 on 2026-05-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_id', models.BigIntegerField(db_index=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('source', models.CharField(choices=[('FRONT_DESK', 'Front Desk'), ('BOOKING', 'Booking'), ('EXPEDIA', 'Expedia'), ('WALK_IN', 'Walk In')], max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='CONFIRMED', max_length=20)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guests.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
