# Generated by Django 6.0.1 on 2026-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_total_amount_reservationguest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='actual_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='actual_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
