# Generated by Django 6.0.4 on 2026-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_description_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=list, help_text="لیست دسترسی\u200cها به صورت JSON. مثال: ['can_view_rooms', 'can_edit_inventory']"),
        ),
    ]
