# Generated by Django 6.0.4 on 2026-05-05 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'گزارش فعالیت', 'verbose_name_plural': 'گزارشات فعالیت'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'نقش', 'verbose_name_plural': 'نقش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.TextField(verbose_name='عملیات'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام نقش'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=list, help_text="لیست دسترسی\u200cها به صورت JSON. مثال: ['can_view_rooms', 'can_edit_inventory']", verbose_name='دسترسی\u200cها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hotel_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='شناسه هتل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='نقش'),
        ),
    ]
