# Generated by Django 6.0.1 on 2026-05-12 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_activitylog_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename')),
                ('name', models.CharField(max_length=200, verbose_name='Display Name')),
            ],
            options={
                'verbose_name': 'Permission Definition',
                'verbose_name_plural': 'Permission Definitions',
            },
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.TextField(verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='is_visible_to_user',
            field=models.BooleanField(default=False, verbose_name='Visible to User'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Duty Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Role Name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='Access (JSON)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hotel_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Hotel ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions_list',
            field=models.ManyToManyField(blank=True, to='accounts.permissiondefinition', verbose_name='Access List'),
        ),
    ]
