# Generated by Django 6.0.1 on 2026-05-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_permissiondefinition_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/avatars/', verbose_name='Avatar'),
        ),
    ]
