# Generated by Django 6.0.1 on 2026-05-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='guest',
            name='national_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
