# Generated by Django 6.0.1 on 2026-05-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_guest_number_guest_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='guests/id_photos/'),
        ),
        migrations.AddField(
            model_name='guest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
