# Generated by Django 6.0.4 on 2026-05-05 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_id', models.BigIntegerField(db_index=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_shifts', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_id', models.BigIntegerField(db_index=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('CARD', 'Card')], max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('terminal_id', models.CharField(blank=True, max_length=40)),
                ('rrn', models.CharField(blank=True, max_length=64)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='folios.folio')),
                ('refunded_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
