# Generated by Django 6.0.1 on 2026-05-12 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('key', models.SlugField(unique=True)),
                ('formula', models.CharField(blank=True, help_text='Simple JS-like formula referencing other keys', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/items/'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_level',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ISSUE', 'Issue Material'), ('RETURN', 'Return Material'), ('REQUEST', 'Request Material'), ('BUY', 'Stock Buy'), ('ADJ', 'Adjustment')], max_length=10),
        ),
    ]
