# Generated by Django 6.0.4 on 2026-05-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorycolumn_remove_inventoryitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_consumable',
            field=models.BooleanField(default=False, verbose_name='Is Consumable (for rooms)'),
        ),
    ]
