# Generated by Django 6.0.4 on 2026-05-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=80)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_id', models.BigIntegerField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('DIRTY', 'Dirty'), ('CLEAN', 'Clean'), ('RESERVED', 'Reserved'), ('OUT_OF_ORDER', 'Out Of Order')], default='CLEAN', max_length=20)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomtype')),
            ],
            options={
                'unique_together': {('hotel_id', 'number')},
            },
        ),
    ]
