# Generated by Django 6.0.4 on 2026-05-05 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_id', models.BigIntegerField(db_index=True)),
                ('number', models.CharField(max_length=10, verbose_name='شماره میز')),
                ('capacity', models.IntegerField(choices=[(2, '2 نفر'), (4, '4 نفر'), (6, '6 نفر')], default=2, verbose_name='ظرفیت')),
                ('status', models.CharField(choices=[('vacant', 'خالی'), ('occupied', 'پر'), ('reserved', 'رزرو')], default='vacant', max_length=20, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'میز',
                'verbose_name_plural': 'میزها',
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'اتاق', 'verbose_name_plural': 'اتاق\u200cها'},
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('single', 'Single'), ('twin', 'Twin'), ('luxury', 'Luxury'), ('king', 'King')], default='king', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_clean',
            field=models.BooleanField(default=True, verbose_name='نظافت شده'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, verbose_name='شماره اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomtype', verbose_name='نوع اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('DIRTY', 'Dirty'), ('CLEAN', 'Clean'), ('RESERVED', 'Reserved'), ('OUT_OF_ORDER', 'Out Of Order')], default='CLEAN', max_length=20, verbose_name='وضعیت'),
        ),
    ]
