# Generated by Django 6.0.4 on 2026-05-05 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_table_alter_room_options_room_category_room_is_clean_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'نوع اتاق', 'verbose_name_plural': 'انواع اتاق'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype', verbose_name='نوع اتاق'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نرخ پایه'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=80, verbose_name='نام نوع اتاق'),
        ),
    ]
