# Generated by Django 6.0.4 on 2026-05-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomtype_options_remove_room_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='name',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='name_en',
            field=models.CharField(default='', max_length=80, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='name_fa',
            field=models.CharField(default='', max_length=80, verbose_name='نام (FA)'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='name_tr',
            field=models.CharField(default='', max_length=80, verbose_name='Name (TR)'),
        ),
    ]
