# Generated by Django 6.0.1 on 2026-05-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_roomtype_name_roomtype_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2, verbose_name='ظرفیت'),
        ),
    ]
