# Generated by Django 6.0.4 on 2026-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_cleaned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین نظافت'),
        ),
    ]
