# Generated by Django 6.0.1 on 2026-05-12 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_last_cleaned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Room Type', 'verbose_name_plural': 'Room Types'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AddField(
            model_name='room',
            name='needs_inventory',
            field=models.BooleanField(default=False, verbose_name='Needs Inventory Restock'),
        ),
        migrations.AddField(
            model_name='room',
            name='needs_maintenance',
            field=models.BooleanField(default=False, verbose_name='Needs Maintenance'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_clean',
            field=models.BooleanField(default=True, verbose_name='Is Clean'),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_cleaned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Cleaned'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype', verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('DIRTY', 'Dirty'), ('CLEAN', 'Clean'), ('RESERVED', 'Reserved'), ('OUT_OF_ORDER', 'Out of Order')], default='CLEAN', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Rate'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name_fa',
            field=models.CharField(default='', max_length=80, verbose_name='Name (FA)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(choices=[(2, '2 Persons'), (4, '4 Persons'), (6, '6 Persons')], default=2, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Table Number'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='vacant', max_length=20, verbose_name='Status'),
        ),
    ]
