# Generated by Django 6.0.4 on 2026-05-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_options_alter_roomtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_restocked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Restocked'),
        ),
    ]
